<a href="https://colab.research.google.com/github/atik-bd/MSc-BA/blob/main/ML_Classification_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

##Data Reading

In [ ]:
# Mounting Google Drive as a data source
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Importing the dataset from google drive
from pandas import read_csv,get_dummies,DataFrame
data1=read_csv('/content/drive/MyDrive/DataSets/bank.csv')

In [ ]:
# Checking the first five rows of the dataset
data1.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [ ]:
# Checking the numbers of rows and columns (features) in the dataset
data1.shape

(4521, 17)

In [ ]:
# Checking the dataset for number of features and data types
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [ ]:
# Checking the basic statistics for the dataset
data1.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

## Data Encoding

In [ ]:
# Binary Encoding_ converting categorical features into numerical binary values
data1['default']=data1['default'].map({'no':1,'yes':0})
data1['housing']=data1['housing'].map({'no':1,'yes':0})
data1['loan']=data1['loan'].map({'no':1,'yes':0})
data1['y']=data1['y'].map({'no':1,'yes':0})
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   int64
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   int64
 7   loan       4521 non-null   int64
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   int64
dtypes: int64(11), object(6)
memory usage: 600.6+ KB

In [ ]:
# Label encoding for ordinal categorical variables
data1['month']=data1['month'].map({'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12})

In [ ]:
# One-Hot Encoding_ converts categorical features into multiple binary columns
data2 = get_dummies(data1,columns=['job','marital','education','contact','poutcome'],dtype=int)
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  4521 non-null   int64
 1   default              4521 non-null   int64
 2   balance              4521 non-null   int64
 3   housing              4521 non-null   int64
 4   loan                 4521 non-null   int64
 5   day                  4521 non-null   int64
 6   month                4521 non-null   int64
 7   duration             4521 non-null   int64
 8   campaign             4521 non-null   int64
 9   pdays                4521 non-null   int64
 10  previous             4521 non-null   int64
 11  y                    4521 non-null   int64
 12  job_admin.           4521 non-null   int64
 13  job_blue-collar      4521 non-null   int64
 14  job_entrepreneur     4521 non-null   int64
 15  job_housemaid        4521 non-null   int64
 16  job_management       4521 non-null   int64
 17  job_retired          4521 non-null   int64
 18  job_self-employed    4521 non-null   int64
 19  job_services         4521 non-null   int64
 20  job_student          4521 non-null   int64
 21  job_technician       4521 non-null   int64
 22  job_unemployed       4521 non-null   int64
 23  job_unknown          4521 non-null   int64
 24  marital_divorced     4521 non-null   int64
 25  marital_married      4521 non-null   int64
 26  marital_single       4521 non-null   int64
 27  education_primary    4521 non-null   int64
 28  education_secondary  4521 non-null   int64
 29  education_tertiary   4521 non-null   int64
 30  education_unknown    4521 non-null   int64
 31  contact_cellular     4521 non-null   int64
 32  contact_telephone    4521 non-null   int64
 33  contact_unknown      4521 non-null   int64
 34  poutcome_failure     4521 non-null   int64
 35  poutcome_other       4521 non-null   int64
 36  poutcome_success     4521 non-null   int64
 37  poutcome_unknown     4521 non-null   int64
dtypes: int64(38)
memory usage: 1.3 MB

## Dividing the dataset

In [ ]:
X=data2.drop('y',axis=1)
Y=data2['y']
print(X.shape)
print(Y.shape)

(4521, 37)
(4521,)

## Data Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
X_scaled=StandardScaler().fit_transform(X)
DataFrame(X_scaled)

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,-1.056270,0.130759,0.121072,1.142051,0.424756,0.374052,1.611873,-0.711861,-0.576829,-0.407218,...,-1.020335,-0.652482,-0.207719,0.749079,-0.267071,-0.643536,-0.348652,-0.213447,-0.171381,0.469300
1,-0.772583,0.130759,1.118644,-0.875617,-2.354292,-0.596026,-0.490631,-0.169194,-0.576829,2.989044,...,0.980070,-0.652482,-0.207719,0.749079,-0.267071,-0.643536,2.868193,-0.213447,-0.171381,-2.130831
2,-0.583458,0.130759,-0.024144,-0.875617,0.424756,0.010273,-0.911131,-0.303898,-0.576829,2.899143,...,-1.020335,1.532609,-0.207719,0.749079,-0.267071,-0.643536,2.868193,-0.213447,-0.171381,-2.130831
3,-1.056270,0.130759,0.017726,-0.875617,-2.354292,-1.566105,-0.070130,-0.250017,0.387967,-0.407218,...,-1.020335,1.532609,-0.207719,-1.334973,-0.267071,1.553915,-0.348652,-0.213447,-0.171381,0.469300
4,1.686036,0.130759,-0.472753,-0.875617,0.424756,-1.323585,-0.490631,-0.146102,-0.576829,-0.407218,...,0.980070,-0.652482,-0.207719,-1.334973,-0.267071,1.553915,-0.348652,-0.213447,-0.171381,0.469300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,-0.772583,0.130759,-0.583410,-0.875617,0.424756,1.707910,0.350371,0.250315,0.709566,-0.407218,...,0.980070,-0.652482,-0.207719,0.749079,-0.267071,-0.643536,-0.348652,-0.213447,-0.171381,0.469300
4517,1.496912,-7.647669,-1.573671,-0.875617,-2.354292,-0.838546,-0.490631,-0.427057,-0.576829,-0.407218,...,-1.020335,1.532609,-0.207719,-1.334973,-0.267071,1.553915,-0.348652,-0.213447,-0.171381,0.469300
4518,1.496912,0.130759,-0.374724,1.142051,0.424756,0.374052,0.770871,-0.434754,2.639160,-0.407218,...,0.980070,-0.652482,-0.207719,0.749079,-0.267071,-0.643536,-0.348652,-0.213447,-0.171381,0.469300
4519,-1.245394,0.130759,-0.094925,1.142051,0.424756,-1.202326,-1.752133,-0.519426,0.387967,1.710451,...,0.980070,-0.652482,-0.207719,0.749079,-0.267071,-0.643536,-0.348652,4.685001,-0.171381,-2.130831
4520,0.267602,0.130759,-0.095257,-0.875617,-2.354292,-1.566105,-0.911131,0.311894,-0.255231,2.090033,...,-1.020335,1.532609,-0.207719,0.749079,-0.267071,-0.643536,-0.348652,4.685001,-0.171381,-2.130831

## Data Splitting

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_scaled,Y,test_size=0.2,random_state=80)
print("X_train:", X_train.shape)
print("X_test:",X_test.shape)
print("Y_train:",Y_train.shape)
print("Y_test:",Y_test.shape)

X_train: (3616, 37)
X_test: (905, 37)
Y_train: (3616,)
Y_test: (905,)

## Data Balancing

In [ ]:
Y_train.value_counts()

y
1    3202
0     414
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE
X_train,Y_train=SMOTE(random_state=70).fit_resample(X_train,Y_train)
Y_train.value_counts()

y
1    3202
0    3202
Name: count, dtype: int64

**bold text**# random forest Using pipeline

# Random Forest Classifier

In [ ]:
# Random Forest Classifier using pipeline (method 3)
from imblearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn import ensemble
RF_classifier = Pipeline([('balancing', SMOTE(random_state = 25)),('classification', ensemble.RandomForestClassifier(criterion='entropy', max_features='sqrt', random_state=100))]) # building classifier
no_trees = {'classification__n_estimators': [250,255,260,265,270,275,280]}
grid_search1 = GridSearchCV(estimator=RF_classifier, param_grid=no_trees, scoring='recall', cv=5)
grid_search1.fit(X_scaled, Y)
best_parameters = grid_search1.best_params_
print(best_parameters)
best_result = grid_search1.best_score_
print(best_result)

{'classification__n_estimators': 270}
0.9455

In [ ]:
# Random Forest Classifier (method 1)
from sklearn import ensemble
RF_classifier1 =ensemble.RandomForestClassifier(n_estimators=270, criterion='entropy', max_features='sqrt', random_state=50)  # building model
RF_classifier1.fit(X_train,Y_train)#training
Y_predRF=RF_classifier1.predict(X_test)# testing

In [ ]:
# Evaluation RF
# Accuracy and confusion matrix
from sklearn import metrics
Accuracy=metrics.accuracy_score(Y_test, Y_predRF) # calculating accuaracy
print("Random Forest Classifier\nAccuracy: ", Accuracy) # Is this a good metric??
con_matrix = metrics.confusion_matrix(Y_test, Y_predRF)
print ("confusion_matrix: \n", con_matrix)
recall = metrics.recall_score(Y_test, Y_predRF)
print ("recall: ",recall)
percision=metrics.precision_score(Y_test, Y_predRF)
print("percision: ",percision)
f1=metrics.f1_score(Y_test, Y_predRF)
print('f1= ',f1)

Random Forest Classifier
Accuracy:  0.8939226519337017
confusion_matrix:
 [[ 52  55]
 [ 41 757]]
recall:  0.9486215538847118
percision:  0.9322660098522167
f1=  0.9403726708074535

# Support Vector Classifier (SVC)

In [ ]:
# Support Vector Classifier using pipeline (method 3)
from imblearn.pipeline import Pipeline
from sklearn import svm
from sklearn.model_selection import GridSearchCV
SV_classifier2 = Pipeline([('balancing', SMOTE(random_state = 1)),('classification', svm.SVC() ) ]) # bulilding classifier
kernels_c = {'classification__kernel': ['linear','poly','rbf','sigmoid'], 'classification__C': [.01,.1,1,10,100]}
grid_search1 = GridSearchCV(estimator=SV_classifier2, param_grid=kernels_c, scoring='recall', cv=5)
grid_search1.fit(X_scaled, Y)
best_parameters = grid_search1.best_params_
print(best_parameters)
best_result = grid_search1.best_score_
print(best_result)

{'classification__C': 0.01, 'classification__kernel': 'poly'}
0.95975

In [ ]:
#building SVM using method#1
from sklearn.svm import SVC
SV_classifier1 = SVC(kernel='poly', C=0.01)  # building classifier
SV_classifier1.fit(X_train, Y_train) # training
Y_predSVC= SV_classifier1.predict(X_test)  #testing

In [ ]:
# Evaluation SVC
# Accuracy and confusion matrix
from sklearn import metrics
Accuracy=metrics.accuracy_score(Y_test, Y_predSVC) # calculating accuaracy
print("Support Vector Classifier\nAccuracy: ", Accuracy) # Is this a good metric??
con_matrix = metrics.confusion_matrix(Y_test, Y_predSVC)
print ("confusion_matrix: \n", con_matrix)
recall = metrics.recall_score(Y_test, Y_predSVC)
print ("recall: ",recall)
percision=metrics.precision_score(Y_test, Y_predSVC)
print("percision: ",percision)
f1=metrics.f1_score(Y_test, Y_predSVC)
print('f1= ',f1)

Support Vector Classifier
Accuracy:  0.8795580110497238
confusion_matrix:
 [[ 34  73]
 [ 36 762]]
recall:  0.9548872180451128
percision:  0.9125748502994012
f1=  0.9332516840171463